#!/bin/bash
echo "Install Dotfiles"

cd ~ && curl -Lk# https://github.com/calyso/dotfiles/tarball/master | tar --strip-components 1 -xz && source .bash_profile

echo "Add snapd Repo"
sudo zypper addrepo --refresh http://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_42.3/ snappy

echo "Refresh Repos and Update System"
sudo zypper ref
sudo zypper up

echo "Install Base Software"
sudo zypper in -y snapd git 

echo "Configure git"
git config --global user.email "mjg1675@gmail.com"
git config --global user.name "Calyso"

echo "Install Base Software from Snap"
sudo snap install slack --classic
sudo snap install spotify
