#!/bin/bash
echo "Install Dotfiles"

cd ~ && curl -Lk# https://github.com/calyso/dotfiles/tarball/master | tar --strip-components 1 -xz && source .bash_profile

echo "Add snapd Repo"
sudo zypper addrepo --refresh http://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_42.3/ snappy

echo "Trust Google Linux Signing Key"
wget https://dl.google.com/linux/linux_signing_key.pub                   
sudo rpm --import linux_signing_key.pub
rm linux_signing_key.pub

echo "Refresh Repos and Update Base Packages"
sudo zypper ref
sudo zypper up

echo "Install Base Software"
sudo zypper ar http://dl.google.com/linux/chrome/rpm/stable/x86_64 google
sudo zypper in -y snapd git remmina google-chrome-stable

echo "Enable snapd Service"
sudo systemctl enable --now snapd.socket

echo "Configure git"
git config --global user.email "mjg1675@gmail.com"
git config --global user.name "Calyso"

echo "Install Base Software from Snap"
sudo snap install slack --classic
sudo snap install spotify discord 
sudo snap install atom --classic
